name: atmtree-env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - python=3.10.13
  - pip=23.3.1
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - datasets=2.15.0
  - evaluate=0.4.1
  - transformers=4.35.2
  - pytorch=2.1.1
  - faiss-cpu=1.7.4
  - pandas=2.1.3
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - pytest=7.4.3
  - graphviz=2.50
  - pip:
    - lshashpy3==2.0.3
    - tqdm==4.66.1
    - jupyter==1.0.0
    - nbformat==5.9.2
